### ISSUE TITLE
features = [ "mio-support" ] causes 100% CPU usage

### ISSUE THREAD

**Issue by howaboutsynergy** [vorner/signal-hook#16]
1. `cargo new somesample`
2. add this to `Cargo.toml`:
```toml
[dependencies]
#signal-hook = { version = "0.1.9" , features = [ "mio-support" ] }  # 100% cpu usage                                           
signal-hook = { version = "0.1.9" , features = [ ] } # no cpu usage!
libc = "0.2.59"
```

3. use this `src/main.rs`:
```rust
extern crate libc;
extern crate signal_hook;

use std::io::Error;
use std::thread;

use signal_hook::iterator::Signals;

fn main() -> Result<(), Error> {
    let signals = Signals::new(&[
        signal_hook::SIGUSR1,
        signal_hook::SIGUSR2,
        signal_hook::SIGHUP,
    ])?;
    thread::spawn(move || {
        for signal in signals.forever() {
            match signal {
                signal_hook::SIGUSR1 => {
                    println!("exiting");
                    break;
                }
                signal_hook::SIGUSR2 => {
                    println!("ignoring {}", signal);
                }
                signal_hook::SIGHUP => {
                    println!("ignoring {}", signal);
                }
                _ => unreachable!(),
            }
        }
    })
    .join()
    .unwrap();
    Ok(())
}

```

4. `cargo run`

When `features = [ "mio-support" ]` is in `Cargo.toml`, `cargo run` will run the program and it will use 100% CPU all the time.
